//! Outbound ポート: アプリが外界（承認・LLM ストリーム等）を使うための trait

pub mod agent_state_storage;
pub mod compaction_strategy;
pub mod approval;
pub mod external_tool_executor;
pub mod dry_run_report_sink;
pub mod command_allow_rules_loader;
pub mod context_message_builder;
pub mod context_pack_builder;
pub mod continue_prompt;
pub mod event_sink_factory;
pub mod lifecycle_hooks;
pub mod interrupt_checker;
pub mod llm_completion;
pub mod llm_event_stream;
pub mod llm_event_stream_factory;
pub mod prepare_session_for_sensitive_check;
pub mod profile_lister;
pub mod resolve_memory_dir;
pub mod resolve_mode_config;
pub mod resolve_system_prompt_from_hooks;
pub mod resolve_profile_and_model;
pub mod run_query;
pub mod session_history_loader;
pub mod session_response_saver;
pub mod task_runner;

pub use agent_state_storage::{AgentStateLoader, AgentStateSaver};
pub use compaction_strategy::CompactionStrategy;
pub use approval::{Approval, ToolApproval};
pub use external_tool_executor::ExternalToolExecutor;
pub use dry_run_report_sink::DryRunReportSink;
pub use command_allow_rules_loader::CommandAllowRulesLoader;
pub use context_message_builder::{ContextMessageBuilder, QueryPlacement};
pub use context_pack_builder::ContextPackBuilder;
pub use continue_prompt::ContinueAfterLimitPrompt;
pub use event_sink_factory::EventSinkFactory;
pub use lifecycle_hooks::LifecycleHooks;
pub use interrupt_checker::InterruptChecker;
pub use llm_completion::LlmCompletion;
pub use llm_event_stream::LlmEventStream;
pub use llm_event_stream_factory::{LlmEventStreamFactory, LlmStreamContext};
pub use prepare_session_for_sensitive_check::PrepareSessionForSensitiveCheck;
pub use profile_lister::ProfileLister;
pub use resolve_memory_dir::ResolveMemoryDir;
pub use resolve_mode_config::ResolveModeConfig;
pub use resolve_system_prompt_from_hooks::ResolveSystemPromptFromHooks;
pub use resolve_profile_and_model::ResolveProfileAndModel;
pub use run_query::RunQuery;
pub use session_history_loader::SessionHistoryLoader;
pub use session_response_saver::SessionResponseSaver;
pub use task_runner::TaskRunner;
