//! Outbound ポート: アプリが外界（承認・LLM ストリーム等）を使うための trait

pub mod approval;
pub mod command_allow_rules_loader;
pub mod config;
pub mod context;
pub mod continue_prompt;
pub mod dry_run_report_sink;
pub mod event_sink_factory;
pub mod interrupt_checker;
pub mod lifecycle_hooks;
pub mod llm;
pub mod policy;
pub mod prompt_source_resolver;
pub mod run_query;
pub mod session;
pub mod package_spec_loader;
pub mod package_resolver;
pub mod skill_spec_loader;
pub mod task_spec_loader;
pub mod tool;

pub use approval::{Approval, ToolApproval};
pub use command_allow_rules_loader::CommandAllowRulesLoader;
pub use common::ports::outbound::{EventAppender, SessionEventStore};
pub use config::*;
pub use context::*;
pub use continue_prompt::ContinueAfterLimitPrompt;
pub use dry_run_report_sink::DryRunReportSink;
pub use event_sink_factory::EventSinkFactory;
pub use interrupt_checker::InterruptChecker;
pub use lifecycle_hooks::LifecycleHooks;
pub use llm::*;
pub use policy::*;
pub use package_resolver::PackageResolver;
pub use package_spec_loader::PackageSpecLoader;
pub use prompt_source_resolver::PromptSourceResolver;
pub use run_query::RunQuery;
pub use session::*;
pub use skill_spec_loader::SkillSpecLoader;
pub use task_spec_loader::TaskSpecLoader;
pub use tool::*;
