//! ai 固有のドメイン型（型と不変条件）

pub mod approval;
pub mod config;
pub mod context;
pub mod dry_run_info;
pub mod external_plugin;
pub mod external_tool_policy_hint;
pub mod history;
pub mod lifecycle;
pub mod memory_kind;
pub mod memory_query;
pub mod memory_scope;
pub mod package_spec;
pub mod policy;
pub mod query;
pub mod resolved;
pub mod resolved_memory_context;
pub mod resolved_package;
pub mod resolved_prompt_source;
pub mod sensitive_filter;
pub mod session;
pub mod skill_spec;
pub mod source_provenance;
pub mod structured_memory_entry;
pub mod task_name;
pub mod task_spec;
pub mod tool;

pub use approval::{Approval, ToolApproval};
pub use common::domain::EventEnvelope;
pub use config::*;
pub use context::*;
pub use dry_run_info::DryRunInfo;
pub use external_tool_policy_hint::*;
pub use history::*;
pub use lifecycle::{LifecycleEvent, QueryOutcome};
pub use memory_kind::MemoryKind;
pub use memory_query::MemoryQuery;
pub use memory_scope::MemoryScope;
pub use package_spec::PackageSpec;
pub use policy::*;
pub use query::*;
pub use resolved::*;
pub use resolved_memory_context::ResolvedMemoryContext;
pub use resolved_package::ResolvedPackage;
pub use resolved_prompt_source::*;
pub use sensitive_filter::*;
pub use skill_spec::SkillSpec;
pub use source_provenance::{SourceProvenance, TaskOriginInfo};
pub use structured_memory_entry::StructuredMemoryEntry;
pub use task_name::TaskName;
pub use task_spec::TaskSpec;
pub use tool::*;
