//! ai 固有のドメイン型（型と不変条件）

pub mod approval;
pub mod budget_report;
pub mod command;
pub mod compaction;
pub mod context_addon;
pub mod context_pack;
pub mod dry_run_info;
pub mod external_plugin;
pub mod config_source;
pub mod resolved;
pub mod config_explain;
pub mod policy_config;
pub mod mode_config;
pub mod context_budget;
pub mod history;
pub mod history_reducer;
pub mod lifecycle;
pub mod manifest;
pub mod memory_entry;
pub mod policy;
pub mod policy_chain;
pub mod policy_explain;
pub mod policy_rule;
pub mod query;
pub mod sensitive_filter;
pub mod task_name;
pub mod tool_capability;
pub mod tool_profile;
pub use approval::{Approval, ToolApproval};
pub use budget_report::*;
pub use command::AiCommand;
pub use context_addon::*;
pub use context_pack::*;
pub use config_source::*;
pub use config_explain::*;
pub use dry_run_info::DryRunInfo;
pub use mode_config::ModeConfig;
pub use compaction::CompactionRecord;
pub use context_budget::ContextBudget;
pub use history::History;
pub use history_reducer::HistoryReducer;
pub use lifecycle::{LifecycleEvent, QueryOutcome};
pub use manifest::{
    hash64, parse_lines, ManifestDecision, ManifestRecordV1, ManifestRole, MessageRecordV1,
};
pub use memory_entry::{MemoryEntry, MemoryMeta};
pub use policy::*;
pub use policy_chain::PolicyChain;
pub use policy_explain::*;
pub use policy_rule::*;
pub use policy_config::*;
pub use query::Query;
pub use sensitive_filter::*;
pub use task_name::TaskName;
pub use tool_capability::*;
pub use tool_profile::*;
pub use resolved::*;
